language: ruby
rvm:
- 2.0.0-p353
notifications:
  webhooks:
  - https://idobata.io/hook/travis_ci/bfa5e14b-6330-40f0-bdb8-36e1ef75ef50
  slack:
    secure: CcN+jR1wDuYiOVWjUqfOy4Y3KFb8i1eMyy8AsBB5x2qyJ2OQrG1vfuxIiivVYBtPjsIfYfGc8VdUwnFg9XmWWlwdeatnncDeM25Lc/nkFZ0l7LVEzThIgf8TozHMVdiWu0GPskjH6S1hVJj2buprjiQXZT/qhDyVmuDataxcXF8=
deploy:
  provider: heroku
  api_key:
    secure: dcBR0IoMcDR+FuKnxDyFTk3kcnk0EUZi2v3x/C35UdYehVbUusr6l/L4X0cJ80gJaDD9jssAjARcxvfJQJiYfOLnpZkgS2vO3GEd/3kTa9mVrCEc8Hr3XTAhUvbyB3tD/NUUrWBh+hPG2bp+wvD7W2nUmWn4mKWYL+aRiBgZUdE=
  run: rake db:setup
  app:
    master: fesdy-info
  on:
    repo: i-d-e-a-t/fesdy
env:
  secure: psZAmsGwDzYS3j8W1TZ8utX/EgvGWbokqvinf1la+Hy+M5o7NkbR3A6WZoTm5V3d6RO2FxyCcl3QkmrMz8/PZ6yZklsV4Ikz4wgEgS/cpu/6zvApLTgvwJfQbPRfNpE258fNEzquyolc1eRQaVQvEnRBBcJYo6/OtZBN0ddEitM=
